app:
  name: TaskWeaver
  description: A code-first agent framework for data analytics tasks
  version: 0.2.0

llm:
  model: gpt-4
  temperature: 0.7
  max_tokens: 4000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0

ui:
  web:
    host: 0.0.0.0
    port: 8000
  gui:
    theme: light
    font_size: 12
    
codegen:
  enabled: true
  api_base: https://api.codegen.sh
  version: v1

